branch-defaults:
  development:
    environment: udagramfront-dev
environment-defaults:
  udagramfront-dev:
    branch: null
    repository: null
global:
  application_name: udagramfront
  default_ec2_keyname: udagramfront
  default_platform: Node.js 10 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
